name: Release alpha version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Aplha release from ${{ github.ref_name }} with ${{ github.event.inputs.manualVersion }} version
        uses: gravity-ui/release-action@v1
        with:
          github-token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          npm-token: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
          node-version: 18
          default-branch: ${{ github.event.inputs.branch }}
          npm-dist-tag: untagged
          npm-preid: alpha
          npm-version: 'prepatch'
          skip-github-release: true
